version: '3.1'
services:
  app:
    container_name: springboot_k8s_app
    image: springboot_k8s_crud_app
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=employees
      - POSTGRES_PASSWORD=root